AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for cross-account access with full permissions for deployment

Parameters:
  EntAwsAccountArn:
    Type: String
    Default: arn:aws:iam::051759900972:role/prod-uswest1-eks-pi-1-20251203221124633900000005
    Description: The AWS ARN that can assume this role

  RoleStsExternalId:
    Type: String
    Default: a6e5f06d-10db-475e-933b-e2efbf89fbe7
    Description: STS ExternalId condition value to use with the role

  RoleName:
    Type: String
    Default: HomeProdAssumeAdmin
    Description: IAM role name

  RolePath:
    Type: String
    Default: /
    Description: Path of IAM role

  RoleDescription:
    Type: String
    Default: Role that allows HomeDev SSO to assume AdministratorAccess role
    Description: IAM Role description

Conditions:
  HasExternalId: !Not [!Equals [!Ref RoleStsExternalId, '']]

Resources:
  EntDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: EntAdditionalPermissions
      Description: Custom policy for permissions in addition to the SecurityAudit policy
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CertificateManagerAccess
            Effect: Allow
            Action:
              - acm:*
            Resource: '*'
          - Sid: OpenSearchServerlessAccess
            Effect: Allow
            Action:
              - aoss:*
            Resource: '*'
          - Sid: AthenaAccess
            Effect: Allow
            Action:
              - athena:*
            Resource: '*'
          - Sid: CostAndUsageReportAccess
            Effect: Allow
            Action:
              - bcm-data-exports:*
            Resource: '*'
          - Sid: BedrockAccess
            Effect: Allow
            Action:
              - bedrock:*
            Resource: '*'
          - Sid: CostExplorerAccess
            Effect: Allow
            Action:
              - ce:*
            Resource: '*'
          - Sid: CloudWatchAccess
            Effect: Allow
            Action:
              - cloudwatch:*
            Resource: '*'
          - Sid: CognitoAccess
            Effect: Allow
            Action:
              - cognito-idp:*
            Resource: '*'
          - Sid: EC2Access
            Effect: Allow
            Action:
              - ec2:*
            Resource: '*'
          - Sid: ECRAccess
            Effect: Allow
            Action:
              - ecr:*
            Resource: '*'
          - Sid: EKSAccess
            Effect: Allow
            Action:
              - eks:*
            Resource: '*'
          - Sid: ElastiCacheAccess
            Effect: Allow
            Action:
              - elasticache:*
            Resource: '*'
          - Sid: ELBAccess
            Effect: Allow
            Action:
              - elasticloadbalancing:*
            Resource: '*'
          - Sid: GlueAccess
            Effect: Allow
            Action:
              - glue:*
            Resource: '*'
          - Sid: GrafanaAccess
            Effect: Allow
            Action:
              - grafana:*
            Resource: '*'
          - Sid: IAMAccess
            Effect: Allow
            Action:
              - iam:*
            Resource: '*'
          - Sid: KendraAccess
            Effect: Allow
            Action:
              - kendra:*
            Resource: '*'
          - Sid: KMSAccess
            Effect: Allow
            Action:
              - kms:*
            Resource: '*'
          - Sid: LambdaAccess
            Effect: Allow
            Action:
              - lambda:*
            Resource: '*'
          - Sid: CloudWatchLogsAccess
            Effect: Allow
            Action:
              - logs:*
            Resource: '*'
          - Sid: RDSAccess
            Effect: Allow
            Action:
              - rds:*
              - rds-db:*
            Resource: '*'
          - Sid: ResourceGroupsAccess
            Effect: Allow
            Action:
              - resource-groups:*
            Resource: '*'
          - Sid: Route53Access
            Effect: Allow
            Action:
              - route53:*
            Resource: '*'
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:*
            Resource: '*'
          - Sid: SageMakerAccess
            Effect: Allow
            Action:
              - sagemaker:*
            Resource: '*'
          - Sid: SecretsManagerAccess
            Effect: Allow
            Action:
              - secretsmanager:*
            Resource: '*'
          - Sid: ShieldAccess
            Effect: Allow
            Action:
              - shield:*
            Resource: '*'
          - Sid: SNSAccess
            Effect: Allow
            Action:
              - sns:*
            Resource: '*'
          - Sid: SQSAccess
            Effect: Allow
            Action:
              - sqs:*
            Resource: '*'
          - Sid: STSAccess
            Effect: Allow
            Action:
              - sts:*
            Resource: '*'
          - Sid: TaggingAccess
            Effect: Allow
            Action:
              - tag:*
            Resource: '*'
          - Sid: WAFAccess
            Effect: Allow
            Action:
              - wafv2:*
            Resource: '*'
          - Sid: XRayAccess
            Effect: Allow
            Action:
              - xray:*
            Resource: '*'

  EntDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Path: !Ref RolePath
      Description: !Ref RoleDescription
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref EntAwsAccountArn
            Action: sts:AssumeRole
            Condition: !If
              - HasExternalId
              - StringEquals:
                  sts:ExternalId: !Ref RoleStsExternalId
              - !Ref AWS::NoValue
      ManagedPolicyArns:
        - !Ref EntDeployPolicy

Outputs:
  RoleArn:
    Description: The ARN of the role
    Value: !GetAtt EntDeployRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn

  RoleName:
    Description: The name of the role
    Value: !Ref EntDeployRole
    Export:
      Name: !Sub ${AWS::StackName}-RoleName

  PolicyArn:
    Description: The ARN of the policy
    Value: !Ref EntDeployPolicy
    Export:
      Name: !Sub ${AWS::StackName}-PolicyArn
